#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys

import nltk


def tag_input_text(text):
    with open('female.txt', 'w') as f, \
            open('male.txt', 'w') as m, \
            open('neutral.txt', 'w') as n:
        training_file_dict = {'m': m, 'n': n, 'f': f}

        for pos_tag in to_pos_tags(text):
            word, _ = pos_tag
            tag = query_tag(pos_tag)
            training_file_dict[tag].write(word + '\n')


def query_tag(question):
    # XXX: workaround to get piped and interactive input
    sys.stdin = open('/dev/tty')
    sys.stdout.write(str(question) + '\nTag (m/n/f) > ')
    tag = input()
    return tag.strip()


def to_pos_tags(text):
    return nltk.pos_tag(nltk.word_tokenize(text))


if __name__ == '__main__':
     tag_input_text(sys.stdin.read())
